/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panels;

/**
 *
 * @author Win 8
 */
public class Invoice extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Invoice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_invoice_savenext = new javax.swing.JButton();
        btn_invoice_close1 = new javax.swing.JButton();
        btn_invoice_savecloase = new javax.swing.JButton();
        btn_invoice_clear = new javax.swing.JButton();
        txt_invoice_search = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_invoice = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        lbl_invoice_date = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl_invoice_invno = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbl_print = new javax.swing.JLabel();
        lbl_settings = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbl_home = new javax.swing.JLabel();
        lbl_minimize = new javax.swing.JLabel();
        lbl_close = new javax.swing.JLabel();
        txt_invoice_total = new javax.swing.JTextField();
        txt_invoice_vat = new javax.swing.JTextField();
        txt_invoice_subtotal = new javax.swing.JTextField();
        lbl_invoice_bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(828, 513));
        jPanel1.setLayout(null);

        btn_invoice_savenext.setText("Save & Next");
        jPanel1.add(btn_invoice_savenext);
        btn_invoice_savenext.setBounds(600, 460, 100, 23);

        btn_invoice_close1.setText("Close");
        btn_invoice_close1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_invoice_close1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_invoice_close1);
        btn_invoice_close1.setBounds(380, 460, 80, 23);

        btn_invoice_savecloase.setText("Save & Close");
        btn_invoice_savecloase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_invoice_savecloaseActionPerformed(evt);
            }
        });
        jPanel1.add(btn_invoice_savecloase);
        btn_invoice_savecloase.setBounds(480, 460, 95, 23);

        btn_invoice_clear.setText("Clear");
        btn_invoice_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_invoice_clearActionPerformed(evt);
            }
        });
        jPanel1.add(btn_invoice_clear);
        btn_invoice_clear.setBounds(280, 460, 80, 23);

        txt_invoice_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_invoice_searchActionPerformed(evt);
            }
        });
        jPanel1.add(txt_invoice_search);
        txt_invoice_search.setBounds(330, 150, 80, 20);

        tbl_invoice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Item No", "Qty", "Item Code", "Description", "Price Each", "Amount"
            }
        ));
        tbl_invoice.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tbl_invoice);
        tbl_invoice.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(290, 180, 510, 180);

        jLabel5.setText("Sub Total");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(650, 370, 50, 20);

        lbl_invoice_date.setText("jLabel4");
        jPanel1.add(lbl_invoice_date);
        lbl_invoice_date.setBounds(640, 90, 110, 14);

        jLabel7.setText("Total Amount");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(640, 424, 64, 20);

        lbl_invoice_invno.setText("jLabel4");
        jPanel1.add(lbl_invoice_invno);
        lbl_invoice_invno.setBounds(340, 90, 110, 14);

        jLabel6.setText("VAT");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(650, 400, 19, 14);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Search");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(280, 150, 60, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Invoice #");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(280, 90, 60, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Date");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(600, 90, 26, 15);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("INVOICE");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(70, 90, 110, 50);

        lbl_print.setForeground(new java.awt.Color(204, 204, 204));
        lbl_print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/report-icon (1).png"))); // NOI18N
        lbl_print.setText("Print");
        jPanel1.add(lbl_print);
        lbl_print.setBounds(530, 30, 70, 30);

        lbl_settings.setForeground(new java.awt.Color(204, 204, 204));
        lbl_settings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/settings icon.png"))); // NOI18N
        lbl_settings.setText("Settings");
        jPanel1.add(lbl_settings);
        lbl_settings.setBounds(710, 30, 80, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/left-arrow.png"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(350, 110, 14, 34);

        lbl_home.setForeground(new java.awt.Color(204, 204, 204));
        lbl_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/gnome_go_home.png"))); // NOI18N
        lbl_home.setText("Home");
        jPanel1.add(lbl_home);
        lbl_home.setBounds(620, 30, 70, 30);

        lbl_minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/1.png"))); // NOI18N
        jPanel1.add(lbl_minimize);
        lbl_minimize.setBounds(770, 10, 20, 16);

        lbl_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/2.png"))); // NOI18N
        jPanel1.add(lbl_close);
        lbl_close.setBounds(800, 10, 20, 16);

        txt_invoice_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_invoice_totalActionPerformed(evt);
            }
        });
        jPanel1.add(txt_invoice_total);
        txt_invoice_total.setBounds(710, 430, 90, 20);

        txt_invoice_vat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_invoice_vatActionPerformed(evt);
            }
        });
        jPanel1.add(txt_invoice_vat);
        txt_invoice_vat.setBounds(710, 400, 90, 20);
        jPanel1.add(txt_invoice_subtotal);
        txt_invoice_subtotal.setBounds(710, 370, 90, 20);

        lbl_invoice_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Untitled-1.jpg"))); // NOI18N
        lbl_invoice_bg.setText("jLabel1");
        jPanel1.add(lbl_invoice_bg);
        lbl_invoice_bg.setBounds(0, 0, 828, 513);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_invoice_savecloaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_invoice_savecloaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_invoice_savecloaseActionPerformed

    private void btn_invoice_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_invoice_clearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_invoice_clearActionPerformed

    private void txt_invoice_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_invoice_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_invoice_searchActionPerformed

    private void btn_invoice_close1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_invoice_close1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_invoice_close1ActionPerformed

    private void txt_invoice_vatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_invoice_vatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_invoice_vatActionPerformed

    private void txt_invoice_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_invoice_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_invoice_totalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Invoice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_invoice_clear;
    private javax.swing.JButton btn_invoice_close1;
    private javax.swing.JButton btn_invoice_savecloase;
    private javax.swing.JButton btn_invoice_savenext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_close;
    private javax.swing.JLabel lbl_home;
    private javax.swing.JLabel lbl_invoice_bg;
    private javax.swing.JLabel lbl_invoice_date;
    private javax.swing.JLabel lbl_invoice_invno;
    private javax.swing.JLabel lbl_minimize;
    private javax.swing.JLabel lbl_print;
    private javax.swing.JLabel lbl_settings;
    private javax.swing.JTable tbl_invoice;
    private javax.swing.JTextField txt_invoice_search;
    private javax.swing.JTextField txt_invoice_subtotal;
    private javax.swing.JTextField txt_invoice_total;
    private javax.swing.JTextField txt_invoice_vat;
    // End of variables declaration//GEN-END:variables
}
